name: CI

# Controls when the workflow will run  ffff
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:



# Jobs
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    #container: maven:3.6.3-openjdk-11-slim

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and test with maven
        run: mvn -s .maven-settings.xml --batch-mode --update-snapshots verify -Dmaven.test.skip=true # We need to skip tests, since we have an ignored test that fails. Remove after feature traces are not needed anymore
        env:
            SECRET_USERNAME: ${{ secrets.USER_NAME }}
            SECRET_USER_TOKEN: ${{ secrets.SECRET_USER_TOKEN }}
